WITH DEMANDA_BAIRRO AS (
    SELECT
        C.ID_CATEGORIA,
        C.NM_CATEGORIA,
        E.NM_BAIRRO,

        COUNT(*) AS TOTAL_SOLICITACOES,

        SUM(
            CASE
                WHEN S.NV_URGENCIA IN ('ALTA', 'CRITICA')
                THEN 1
                ELSE 0
            END
        ) AS TOTAL_ALTA_OU_CRITICA

    FROM T_ETP_SOLICITACAO S

    INNER JOIN T_ETP_SUBSERVICO SS
        ON SS.ID_SUBSERVICO = S.ID_SUBSERVICO

    INNER JOIN T_ETP_CATEGORIA C
        ON C.ID_CATEGORIA = SS.ID_CATEGORIA

    INNER JOIN T_ETP_ENDERECO E
        ON E.ID_ENDERECO = S.ID_ENDERECO

    WHERE S.ST_SOLICITACAO <> 'CANCELADA'

    GROUP BY
        C.ID_CATEGORIA,
        C.NM_CATEGORIA,
        E.NM_BAIRRO
),

RANKING_DEMANDA AS (
    SELECT
        DEMANDA_BAIRRO.*,

        DENSE_RANK() OVER (
            PARTITION BY ID_CATEGORIA
            ORDER BY TOTAL_SOLICITACOES DESC
        ) AS POSICAO_CATEGORIA,

        ROUND(
            TOTAL_SOLICITACOES * 100
            / NULLIF(
                SUM(TOTAL_SOLICITACOES) OVER (
                    PARTITION BY ID_CATEGORIA
                ),
                0
            ),
            2
        ) AS PERCENTUAL_CATEGORIA

    FROM DEMANDA_BAIRRO
)

SELECT
    NM_CATEGORIA AS CATEGORIA,
    NM_BAIRRO AS BAIRRO,
    TOTAL_SOLICITACOES,
    TOTAL_ALTA_OU_CRITICA,
    PERCENTUAL_CATEGORIA,
    POSICAO_CATEGORIA

FROM RANKING_DEMANDA

WHERE POSICAO_CATEGORIA <= 3

ORDER BY
    NM_CATEGORIA,
    POSICAO_CATEGORIA,
    NM_BAIRRO;