spring.application.name=enterprise-challenge3

spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

server.error.include-message=always
server.error.include-stacktrace=never

server.port=8080
govatende.ia.base-url=http://127.0.0.1:8000