spring.datasource.url=jdbc:oracle:thin:@//oracle.fiap.com.br:1521/orcl
spring.datasource.username=rm564119
spring.datasource.password=150302
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

jwt.secret=s0bXwxCRu6GaUI4nQYKBPMw7exly6hAmhqObITWRbeU=
jwt.expiration-ms=3600000

app.cors.allowed-origin=http://localhost:3000

app.upload.dir=uploads

app.setup.auditor-key=GovAtende-Setup-2026

govatende.ia.base-url=http://127.0.0.1:8000
govatende.ia.url=http://127.0.0.1:8000