package br.com.fiap.enterprise_challenge3.model.enums;

public enum AcaoAuditoria {
    LOGIN,
    CRIACAO_AUDITOR,
    CONSULTA_DADOS_PESSOAIS,
    ATUALIZACAO_PERFIL,
    DESATIVACAO_CIDADAO,
    CANCELAMENTO_SOLICITACAO,
    ALTERACAO_STATUS_SOLICITACAO,
    CONSULTA_RELATORIO,
    EXPORTACAO_RELATORIO,
    DOWNLOAD_ANEXO,
    CONSULTA_AUDITORIA,
    EXCLUSAO_REGISTRO,
    ACESSO_NEGADO
}